<?php

/**
 * @file
 * Static generation module file.
 */

 use Drupal\Core\Url;

/**
 * Implements hook_toolbar().
 */
function static_generator_toolbar() {
  $items['publish'] = [
    '#type' => 'toolbar_item',
    'tab' => [
      '#type' => 'link',
      '#title' => t('Publish'),
      '#url' => Url::fromRoute('static_generator.static'),
      '#weight' => 100,
      '#attributes' => [
        'title' => t('Publish static website'),
        'class' => ['toolbar-icon'],
      ],
    ],
    '#wrapper_attributes' => [
      'class' => ['publish-toolbar-tab'],
    ],
  ];

  return $items;
}

/**
 * Implements hook_form_alter().
 */
function static_generator_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  // Alter forms if necessary.
}
