name: Deploy to Cloudflare Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.4'  # Check for the required PHP version for Drupal

    - name: Generate Static HTML
      run: php scripts/generate_static_html.php  # This script should be implemented to generate static HTML

    - name: Deploy to Cloudflare Pages
      uses: cloudflare/wrangler-action@1.3.0
      with:
        apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        environment: 'production'
